services:
  captcha-dev:
    build:
      dockerfile: ./Dockerfile
      context: ./
    image: captcha:local
    entrypoint: "tail -f /dev/null"
    ports: 
      - "127.0.0.1:8000:8000"
    expose:
      - 8000
    depends_on:
      - postgres
    volumes:
      - ./src:/workspace/src
      - ./.vscode:/workspace/.vscode
      - ./settings.yml:/workspace/settings.yml
      - ./test:/workspace/test
      - ./requirements-test.txt:/workspace/requirements-test.txt
    environment:
      DB_PASSWORD : postgres
      DB_PORT : 5432
      SERVICE_HOST : 0.0.0.0
      SERVICE_PORT : 8000
  
  captcha:
    image: captcha:local
    ports: 
      - "127.0.0.1:8088:8088"
    expose:
      - "8088"
    depends_on:
      - postgres
    environment:
      DB_PASSWORD : postgres
      DB_PORT : 5432
      SERVICE_HOST : 0.0.0.0
      SERVICE_PORT : 8088

  
  postgres:
    image: postgres:11
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432